# Generated by Django 4.2.2 on 2023-06-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="devices",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
